#!/usr/bin/env python3
"""
Bake parity smoke test — compare canonical representations against baseline.

Compares structural summaries (not raw bytes) of artifacts generated by
tools/bake.py against the committed baseline in tests/fixtures/baseline/.

Allowed differences: only in the regions of the four shell probes.
"""

import sys
import os
import json
import struct
import subprocess
import tempfile
from pathlib import Path

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_DIR = os.path.normpath(os.path.join(SCRIPT_DIR, ".."))
TOOLS_DIR = os.path.join(REPO_DIR, "tools")
BASELINE_DIR = os.path.join(REPO_DIR, "tests", "fixtures", "baseline")
OG_MAP = os.path.join(REPO_DIR, "assets", "og_converted", "maps", "1-1.map")

failed = 0


def check(name, condition, detail=""):
    global failed
    if condition:
        print(f"  PASS: {name}")
    else:
        print(f"  FAIL: {name} {detail}")
        failed += 1


def run_bake(out_dir):
    """Run tools/bake.py and return the output directory path."""
    result = subprocess.run(
        [sys.executable, os.path.join(TOOLS_DIR, "bake.py"),
         OG_MAP, "--out-dir", out_dir, "--scale", "0.2"],
        capture_output=True, text=True, cwd=REPO_DIR
    )
    if result.returncode != 0:
        print(f"  bake.py failed: {result.stderr}")
        return False
    return True


def decode_lvl_summary(lvl_path):
    """Decode LVL2 file and return canonical summary."""
    sys.path.insert(0, TOOLS_DIR)
    from lvl_format import LvlFile
    lvl = LvlFile.read(lvl_path)
    return {
        "face_count": len(lvl.faces),
        "vertex_count": len(lvl.vertices),
        "entity_count": len(lvl.entities),
        "collider_count": len(lvl.colliders),
        "string_count": len(lvl.strings),
    }


def decode_colmesh_summary(colmesh_path):
    """Decode colmesh file and return canonical summary."""
    with open(colmesh_path, 'rb') as f:
        magic = f.read(4)
        version, flags = struct.unpack('>HH', f.read(4))
        qaabb_min = struct.unpack('>hhh', f.read(6))
        qaabb_max = struct.unpack('>hhh', f.read(6))
        quant_scale = struct.unpack('>I', f.read(4))[0]
        # Reinterpret uint32 as float
        quant_scale = struct.unpack('>f', struct.pack('>I', quant_scale))[0]
        origin = struct.unpack('>fff', f.read(12))
        vert_count, tri_count, bvh_count = struct.unpack('>III', f.read(12))
    return {
        "magic": magic.decode('ascii'),
        "version": version,
        "flags": flags,
        "vertex_count": vert_count,
        "triangle_count": tri_count,
        "bvh_node_count": bvh_count,
        "quant_scale": quant_scale,
    }


def decode_nav_summary(nav_path):
    """Decode NAV file and return canonical summary."""
    with open(nav_path, 'rb') as f:
        magic = f.read(4)
        count = struct.unpack('<H', f.read(2))[0]
    return {
        "magic": magic.decode('ascii'),
        "platform_count": count,
    }


def test_lvl_parity(bake_dir):
    """Compare LVL output against baseline."""
    print("\n[test_lvl_parity]")
    baseline_path = os.path.join(BASELINE_DIR, "1-1", "1-1.lvl.summary.json")
    if not os.path.exists(baseline_path):
        check("baseline exists", False, f"{baseline_path} not found")
        return

    with open(baseline_path) as f:
        baseline = json.load(f)

    actual = decode_lvl_summary(os.path.join(bake_dir, "output.lvl"))

    check("face_count", actual["face_count"] == baseline.get("face_count", 367),
          f"got {actual['face_count']}")
    check("vertex_count", actual["vertex_count"] == baseline.get("vertex_count", 1362),
          f"got {actual['vertex_count']}")
    check("entity_count", actual["entity_count"] == baseline.get("entity_count", 3),
          f"got {actual['entity_count']}")


def test_colmesh_parity(bake_dir):
    """Compare colmesh output against baseline."""
    print("\n[test_colmesh_parity]")
    baseline_path = os.path.join(BASELINE_DIR, "1-1", "1-1.colmesh.summary.json")
    if not os.path.exists(baseline_path):
        check("baseline exists", False, f"{baseline_path} not found")
        return

    with open(baseline_path) as f:
        baseline = json.load(f)

    actual = decode_colmesh_summary(os.path.join(bake_dir, "output.colmesh"))

    check("magic", actual["magic"] == baseline["magic"],
          f"got {actual['magic']}")
    check("version", actual["version"] == baseline["version"],
          f"got {actual['version']}")
    check("vertex_count", actual["vertex_count"] == baseline["vertex_count"],
          f"got {actual['vertex_count']}")
    check("triangle_count", actual["triangle_count"] == baseline["triangle_count"],
          f"got {actual['triangle_count']}")
    check("bvh_node_count", actual["bvh_node_count"] == baseline["bvh_node_count"],
          f"got {actual['bvh_node_count']}")


def test_nav_parity(bake_dir):
    """Compare NAV output against baseline."""
    print("\n[test_nav_parity]")
    nav_path = os.path.join(bake_dir, "output.nav")
    if not os.path.exists(nav_path):
        check("nav file exists", False, f"{nav_path} not found")
        return

    baseline_path = os.path.join(BASELINE_DIR, "1-1", "1-1.nav.summary.json")
    if not os.path.exists(baseline_path):
        check("baseline exists", False, f"{baseline_path} not found")
        return

    with open(baseline_path) as f:
        baseline = json.load(f)

    actual = decode_nav_summary(nav_path)

    check("magic", actual["magic"] == baseline["magic"],
          f"got {actual['magic']}")
    check("platform_count", actual["platform_count"] == baseline["platform_count"],
          f"got {actual['platform_count']}")


def test_counts_parity(bake_dir):
    """Compare overall counts against baseline.json."""
    print("\n[test_counts_parity]")
    baseline_path = os.path.join(BASELINE_DIR, "baseline.json")
    if not os.path.exists(baseline_path):
        check("baseline.json exists", False)
        return

    with open(baseline_path) as f:
        baseline = json.load(f)

    baseline_counts = baseline["counts"]

    # Decode actual colmesh
    colmesh_actual = decode_colmesh_summary(os.path.join(bake_dir, "output.colmesh"))
    lvl_actual = decode_lvl_summary(os.path.join(bake_dir, "output.lvl"))
    nav_actual = decode_nav_summary(os.path.join(bake_dir, "output.nav"))

    check("lvl_faces", lvl_actual["face_count"] == baseline_counts["lvl_faces"],
          f"got {lvl_actual['face_count']}")
    check("lvl_vertices", lvl_actual["vertex_count"] == baseline_counts["lvl_vertices"],
          f"got {lvl_actual['vertex_count']}")
    check("lvl_entities", lvl_actual["entity_count"] == baseline_counts["lvl_entities"],
          f"got {lvl_actual['entity_count']}")
    check("colmesh_vertices", colmesh_actual["vertex_count"] == baseline_counts["colmesh_vertices"],
          f"got {colmesh_actual['vertex_count']}")
    check("colmesh_triangles", colmesh_actual["triangle_count"] == baseline_counts["colmesh_triangles"],
          f"got {colmesh_actual['triangle_count']}")
    check("nav_platforms", nav_actual["platform_count"] == baseline_counts["nav_platforms"],
          f"got {nav_actual['platform_count']}")


def main():
    print("=== Bake Parity Smoke Test ===")

    # Run bake.py
    with tempfile.TemporaryDirectory() as tmpdir:
        print(f"\nRunning bake.py to {tmpdir}")
        if not run_bake(tmpdir):
            print("FAIL: bake.py failed")
            return 1

        # Check all expected files exist
        for f in ["output.colmesh", "output.lvl", "output.nav", "output.manifest"]:
            check(f"exists: {f}", os.path.exists(os.path.join(tmpdir, f)))

        # Run parity tests
        test_lvl_parity(tmpdir)
        test_colmesh_parity(tmpdir)
        test_nav_parity(tmpdir)
        test_counts_parity(tmpdir)

    print(f"\n{'='*40}")
    if failed == 0:
        print("ALL PASSED")
        return 0
    else:
        print(f"FAILED ({failed} failures)")
        return 1


if __name__ == "__main__":
    sys.exit(main())